name: Develop Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: build and push image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME  }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        repository: rwandaopensource/api-opensource
        tags: staging

    - name: trigger netlify build hooks
      uses: wei/curl@v1
      with:
        args: -X POST -d '{}' ${{ secrets.STAGING_BUILD_HOOK }}